### ISSUE TITLE
theme does not work with 4.0.0

### ISSUE THREAD

**Issue by akankov** [select2/select2-bootstrap-theme#8]
theme does not work with 4.0.0

**Comment by kvikram1988** [comment]
Its working for me ... did you use the below code??
`$.fn.select2.defaults.set( "theme", "bootstrap" );`

**Comment by akankov** [comment]
Take a look at your example page
http://fk.github.io/select2-bootstrap-theme/

**Comment by kvikram1988** [comment]
OK Yaa... Not everything is working.... especially multi-select selectboxes.

**Comment by fk** [comment]
See https://github.com/fk/select2-bootstrap-theme/issues/9#issuecomment-97184718 for a temporary workaround.

**Comment by fk** [comment]
See https://github.com/fk/select2-bootstrap-theme/issues/9#issuecomment-97184718 for temporary fixes.

**Comment by fk** [comment]
Fixed in v0.1.0-beta.2.

**Comment by micayael** [comment]
Hi. Not fixed for me using beta2.

I am using "bootstrap-sass-official": "~3.3.3" importing into my own sass styles at the first line like this:

```
@import "../vendor/bootstrap-sass-official/assets/stylesheets/_bootstrap.scss";
/* my own styles */
```

So, when I import the styles into my html page I have this order:
1. select2.css
2. select2-bootstrap.css
3. my-css.css -> which include the bootstrap css

At the documentation page we have this order:
1. bootstrap.css
2. select2.css
3. select2-bootstrap.css
4. own.css

So if I change this line 

```
.form-control.select2-hidden-accessible {
  position: absolute;
}
```

to this, it works

```
.form-control.select2-hidden-accessible {
  position: absolute !important;
}
```

**Comment by fk** [comment]
@micayael Should be fixed in 0.1.0-beta.3.

**Comment by micayael** [comment]
It Works great!! Thanks
